spring.application.name=test

spring.datasource.url=jdbc:postgresql://localhost:5432/lrucachetestdb
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cache.capacity=5
